CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS schema_version_probe (
    id INTEGER PRIMARY KEY,
    installed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
